default: &default
  host: localhost
  user: root
  password: "123456"
  adapter: postgres

development:
  <<: *default
  db: multiverse

test:
  <<: *default
  db: multiverse_test

production:
  <<: *default
  db: multiverse_production